# Q1. What is the total revenue and number of orders in the dataset?
SELECT SUM(total_amount) AS total_revenue, COUNT(*) AS total_orders 
FROM Orders;

# Q2. What is the daily sales trend (total revenue per day)?
SELECT order_date, SUM(total_amount) AS daily_revenue, COUNT(*) AS orders_count 
FROM Orders 
GROUP BY order_date 
ORDER BY order_date;

# Q3. What is the average order value?
SELECT SUM(total_amount) / COUNT(*) AS avg_order_value 
FROM Orders;

# Q4. What is the total quantity and revenue generated by each product?
SELECT p.product_id, p.product_name, SUM(oi.quantity) AS total_quantity_sold, SUM(oi.quantity * oi.item_price) AS total_revenue
FROM Order_Items oi 
JOIN Products p ON oi.product_id = p.product_id 
GROUP BY p.product_id, p.product_name 
ORDER BY total_revenue DESC;

# Q5. Which are the top 5 best-selling products by revenue?
SELECT p.product_id, p.product_name, SUM(oi.quantity * oi.item_price) AS total_revenue 
FROM Order_Items oi 
JOIN Products p ON oi.product_id = p.product_id 
GROUP BY p.product_id, p.product_name 
ORDER BY total_revenue DESC LIMIT 5;

# Q6. What is the total revenue by product category?
SELECT p.category, SUM(oi.quantity * oi.item_price) AS category_revenue, SUM(oi.quantity) AS total_units_sold
FROM Order_Items oi
JOIN Products p ON oi.product_id = p.product_id
GROUP BY p.category
ORDER BY category_revenue DESC;

# Q7. What is the total spend and number of orders for each customer?
SELECT c.customer_id, c.name, c.city, COUNT(o.order_id) AS total_orders, SUM(o.total_amount) AS total_spent
FROM Customers c
JOIN Orders o ON c.customer_id = o.customer_id
GROUP BY c.customer_id, c.name, c.city
ORDER BY total_spent DESC;

# Q8. Who are the top 5 customers by total spend?
SELECT c.customer_id, c.name, SUM(o.total_amount) AS total_spent
FROM Customers c
JOIN Orders o ON c.customer_id = o.customer_id
GROUP BY c.customer_id, c.name
ORDER BY total_spent DESC
LIMIT 5;

# Q9. Which city generates the highest revenue?
SELECT c.city, SUM(o.total_amount) AS city_revenue, COUNT(DISTINCT c.customer_id) AS unique_customers
FROM Customers c
JOIN Orders o ON c.customer_id = o.customer_id
GROUP BY c.city
ORDER BY city_revenue DESC;

# Q10. What is the average number of items per order?
SELECT AVG(items_count) AS avg_items_per_order
FROM (SELECT order_id, SUM(quantity) AS items_count
    FROM Order_Items
    GROUP BY order_id
) t;

# Q11. List all high-value orders (e.g., total_amount > 300).
SELECT o.order_id, o.order_date, c.name AS customer_name, o.total_amount
FROM Orders o
JOIN Customers c ON o.customer_id = c.customer_id
WHERE o.total_amount > 300
ORDER BY o.total_amount DESC;

# Q12. Show a detailed line-item view of each order (for invoice-style reporting).
SELECT o.order_id, o.order_date, c.name AS customer_name, 
p.product_name, oi.quantity, oi.item_price, (oi.quantity * oi.item_price) AS line_total
FROM Orders o
JOIN Customers c ON o.customer_id = c.customer_id
JOIN Order_Items oi ON o.order_id = oi.order_id
JOIN Products p ON oi.product_id = p.product_id
ORDER BY o.order_id, p.product_name;

# Q13. Compare regular price vs actual selling price to see discounts.
SELECT 
p.product_id, p.product_name, p.price AS regular_price, AVG(oi.item_price) AS avg_selling_price
FROM Order_Items oi 
JOIN Products p ON oi.product_id = p.product_id
GROUP BY p.product_id, p.product_name, p.price
ORDER BY (p.price - AVG(oi.item_price)) DESC;

# Q14. Find all items that were given for free (item_price = 0).
SELECT o.order_id, o.order_date, c.name AS customer_name, p.product_name, oi.quantity
FROM Order_Items oi
JOIN Orders o ON oi.order_id = o.order_id
JOIN Customers c ON o.customer_id = c.customer_id
JOIN Products p ON oi.product_id = p.product_id
WHERE oi.item_price = 0;
